### ISSUE TITLE
User agent from python-requests

### ISSUE THREAD

**Issue by Aprillion** [shon/httpagentparser#71]
https://pypi.python.org/pypi/requests is sending a custom user agent string, including the its version, version of python, e.g.: `python-requests/2.7.0 CPython/2.7.10 Darwin/14.3.0`
It would be nice if httpagentparser recognize the most common non-browser user agents, at least the python one :)

**Comment by shon** [comment]
@Aprillion httpagentparser does detect python requests. But Python requests probably not among top browsers so it is available via `more` module.

```python
import httpagentparser
import httpagentparser.more
s = 'python-requests/2.7.0 CPython/2.7.10 Darwin/14.3.0'
print(httpagentparser.detect(s))
```

**Comment by Aprillion** [comment]
ah, I just didn't discover the .more modifier by reading the readme, thanks.
