### ISSUE TITLE
getting `platform` name value as None

### ISSUE THREAD

**Issue by PramodBisht** [shon/httpagentparser#72]
I tried to authenticate my website through Facebook using social auth, but in some case I am getting platform as None, which is breaking the functionality of my website.
Browser Used: Chrome

Note: I am unable to provide the Agent string because we were unable to log that.

Kindly help me on that.

**Comment by shon** [comment]
If platform can not detected reliably value is set to None. Until I can see user agent string for which this is happening I can not comment whether this is a bug.

**Comment by PramodBisht** [comment]
@shon this is my agent string "Apache-HttpClient/UNAVAILABLE (java 1.4)"
