### ISSUE TITLE
classifiers not including python 2.x

### ISSUE THREAD

**Issue by brianjmurrell** [shon/httpagentparser#73]
According to the [README.md](https://github.com/shon/httpagentparser/blob/master/README.md) your package supports Python 2.5+ but the [classifiers](https://github.com/shon/httpagentparser/blob/8bfc1c9b393d83da5544f392bbbe57cf7e7d2ff3/setup.py#L51) says only Python 3.

This misleads [software](https://github.com/fedora-python/pyp2rpm) that is interpreting the `setup.py` into not building the full compliment of packages that it could.

**Comment by shon** [comment]
Ah. Thanks for reporting. Will check it tonight.
