### ISSUE TITLE
Chrome in Nexus 5 is detected as Opera

### ISSUE THREAD

**Issue by id0Sch** [shon/httpagentparser#75]
the following user agent is detected as opera
```
Mozilla/5.0 (Linux; Android 8.0.0; Nexus 5X Build/OPR6.170623.023) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/62.0.3202.84 Mobile Safari/537.36
```
the problem is: `OPR6.170623.023`

I would appreciate your assistance since its affecting production,
thanks.

**Comment by shon** [comment]
@id0Sch thanks for reporting. Released new version of `httpagentparser`.

**Comment by id0Sch** [comment]
Thanks so much for the rapid response! 
will update today
🍾
